questions = [
    {"question": "What is the capital of Alabama?", "choices": ["Montgomery", "Birmingham", "Mobile", "Huntsville"], "answer": "Montgomery"},
    {"question": "What is the capital of Alaska?", "choices": ["Juneau", "Anchorage", "Fairbanks", "Sitka"], "answer": "Juneau"},
    {"question": "What is the capital of Arizona?", "choices": ["Phoenix", "Tucson", "Mesa", "Chandler"], "answer": "Phoenix"},
    {"question": "What is the capital of Arkansas?", "choices": ["Little Rock", "Fayetteville", "Springdale", "Fort Smith"], "answer": "Little Rock"},
    {"question": "What is the capital of California?", "choices": ["Sacramento", "Los Angeles", "San Francisco", "San Diego"], "answer": "Sacramento"},
    {"question": "What is the capital of Colorado?", "choices": ["Denver", "Colorado Springs", "Aurora", "Fort Collins"], "answer": "Denver"},
    {"question": "What is the capital of Connecticut?", "choices": ["Hartford", "New Haven", "Stamford", "Bridgeport"], "answer": "Hartford"},
    {"question": "What is the capital of Delaware?", "choices": ["Dover", "Wilmington", "Newark", "Middletown"], "answer": "Dover"},
    {"question": "What is the capital of Florida?", "choices": ["Tallahassee", "Miami", "Orlando", "Tampa"], "answer": "Tallahassee"},
    {"question": "What is the capital of Georgia?", "choices": ["Atlanta", "Augusta", "Savannah", "Columbus"], "answer": "Atlanta"},
    {"question": "What is the capital of Hawaii?", "choices": ["Honolulu", "Hilo", "Kailua", "Kapolei"], "answer": "Honolulu"},
    {"question": "What is the capital of Idaho?", "choices": ["Boise", "Meridian", "Nampa", "Idaho Falls"], "answer": "Boise"},
    {"question": "What is the capital of Illinois?", "choices": ["Springfield", "Chicago", "Naperville", "Peoria"], "answer": "Springfield"},
    {"question": "What is the capital of Indiana?", "choices": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"], "answer": "Indianapolis"},
    {"question": "What is the capital of Iowa?", "choices": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"], "answer": "Des Moines"},
    {"question": "What is the capital of Kansas?", "choices": ["Topeka", "Wichita", "Overland Park", "Kansas City"], "answer": "Topeka"},
    {"question": "What is the capital of Kentucky?", "choices": ["Frankfort", "Louisville", "Lexington", "Bowling Green"], "answer": "Frankfort"},
    {"question": "What is the capital of Louisiana?", "choices": ["Baton Rouge", "New Orleans", "Shreveport", "Lafayette"], "answer": "Baton Rouge"},
    {"question": "What is the capital of Maine?", "choices": ["Augusta", "Portland", "Bangor", "Lewiston"], "answer": "Augusta"},
    {"question": "What is the capital of Maryland?", "choices": ["Annapolis", "Baltimore", "Frederick", "Rockville"], "answer": "Annapolis"},
    {"question": "What is the capital of Massachusetts?", "choices": ["Boston", "Worcester", "Springfield", "Cambridge"], "answer": "Boston"},
    {"question": "What is the capital of Michigan?", "choices": ["Lansing", "Detroit", "Grand Rapids", "Ann Arbor"], "answer": "Lansing"},
    {"question": "What is the capital of Minnesota?", "choices": ["Saint Paul", "Minneapolis", "Rochester", "Duluth"], "answer": "Saint Paul"},
    {"question": "What is the capital of Mississippi?", "choices": ["Jackson", "Gulfport", "Southaven", "Biloxi"], "answer": "Jackson"},
    {"question": "What is the capital of Missouri?", "choices": ["Jefferson City", "Kansas City", "Saint Louis", "Springfield"], "answer": "Jefferson City"},
    {"question": "What is the capital of Montana?", "choices": ["Helena", "Billings", "Missoula", "Great Falls"], "answer": "Helena"},
    {"question": "What is the capital of Nebraska?", "choices": ["Lincoln", "Omaha", "Bellevue", "Grand Island"], "answer": "Lincoln"},
    {"question": "What is the capital of Nevada?", "choices": ["Carson City", "Las Vegas", "Reno", "Henderson"], "answer": "Carson City"},
    {"question": "What is the capital of New Hampshire?", "choices": ["Concord", "Manchester", "Nashua", "Derry"], "answer": "Concord"},
    {"question": "What is the capital of New Jersey?", "choices": ["Trenton", "Newark", "Jersey City", "Paterson"], "answer": "Trenton"},
    {"question": "Who wrote 'Pride and Prejudice'?", "choices": ["Jane Austen", "Charlotte Bronte", "Mark Twain", "Charles Dickens"], "answer": "Jane Austen"},
    {"question": "What is the smallest planet in our solar system?", "choices": ["Mercury", "Venus", "Earth", "Mars"], "answer": "Mercury"},
    {"question": "Who painted the Mona Lisa?", "choices": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Claude Monet"], "answer": "Leonardo da Vinci"},
    {"question": "What is the largest ocean on Earth?", "choices": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "answer": "Pacific Ocean"},
    {"question": "What year did the Titanic sink?", "choices": ["1912", "1905", "1898", "1923"], "answer": "1912"},
    {"question": "Who developed the theory of relativity?", "choices": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Marie Curie"], "answer": "Albert Einstein"},
    {"question": "What is the capital of Australia?", "choices": ["Canberra", "Sydney", "Melbourne", "Brisbane"], "answer": "Canberra"},
    {"question": "What is the largest country by area?", "choices": ["Russia", "Canada", "China", "United States"], "answer": "Russia"}
]